CREATE TYPE role_type AS enum('admin','user');

CREATE TABLE IF NOT EXISTS users(
	id SERIAL PRIMARY KEY,
	mobile VARCHAR(20) UNIQUE NOT NULL,
	username VARCHAR(255) NOT NULL,
	password VARCHAR(255),
	role role_type NOT NULL DEFAULT 'user',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);